#!/usr/bin/env -S deno run --allow-read --allow-write --allow-env --allow-net --allow-ffi
/**
 * `sisal` migration CLI.
 *
 * The command runner is injectable for tests. The executable path lazily loads
 * dialect adapters only after a command resolves its configured dialect.
 *
 * @module
 */

import {
  isSisalLogLevel,
  type Logger,
  type SisalDialectName,
  type SisalLoggingOptions,
  type SisalLogLevel,
  type SisalLogSettings,
  type SisalSchemaSnapshot,
} from "@sisal/core";
import {
  buildMigrationFile,
  checkDrift,
  defineConfig,
  defineMigration,
  defineSqlMigration,
  denoMigrationFileSystem,
  type DiscoveredMigration,
  type DriftReport,
  type MigrateConfig,
  type MigrateProvider,
  type Migration,
  MigrationError,
  type MigrationFileSystem,
  type MigrationPlan,
  type MigrationResult,
  type MigrationRunOptions,
  nextMigrationSequence,
  readMigrationsDir,
  type SchemaChange,
  splitSqlStatements,
  writeMigrationFile,
} from "./mod.ts";

/** The dialects the `sisal` migration CLI can target. */
type CliDialect = "postgres" | "sqlite" | "mysql";
/** Sink for one line of CLI output — stdout by default, injectable for tests. */
type CliOutput = (line: string) => void;

/**
 * A database target `sisal init` can scaffold a config for.
 *
 * To support a new database, add one entry to {@link INIT_TARGETS}; nothing else
 * in the CLI needs to change. `dialect` is the SQL dialect written to the config
 * (drives DDL); `connection` is the commented connection hints for that target.
 */
interface InitTarget {
  readonly id: string;
  readonly aliases: readonly string[];
  readonly label: string;
  readonly dialect: CliDialect;
  /** Runtime adapter override written to the config (e.g. Neon over HTTP). */
  readonly provider?: MigrateProvider;
  readonly connection: readonly string[];
}

const INIT_TARGETS: readonly InitTarget[] = [
  {
    id: "postgres",
    aliases: ["pg", "postgresql"],
    label: "PostgreSQL",
    dialect: "postgres",
    connection: ['  // databaseUrl: Deno.env.get("DATABASE_URL"),'],
  },
  {
    id: "neon",
    aliases: ["neon-http"],
    label: "Neon (serverless PostgreSQL)",
    dialect: "postgres",
    provider: "neon",
    connection: [
      "  // Neon serverless (HTTP) — migrations apply one statement per call:",
      '  // databaseUrl: Deno.env.get("DATABASE_URL"),',
    ],
  },
  {
    id: "sqlite",
    aliases: [],
    label: "SQLite",
    dialect: "sqlite",
    connection: ['  // databasePath: "app.db",'],
  },
  {
    id: "libsql",
    aliases: ["turso"],
    label: "libSQL / Turso",
    dialect: "sqlite",
    connection: [
      "  // Local file, or a remote libSQL/Turso database:",
      '  // databaseUrl: Deno.env.get("TURSO_DATABASE_URL") ?? "file:app.db",',
      '  // databaseAuthToken: Deno.env.get("TURSO_AUTH_TOKEN"),',
    ],
  },
  {
    id: "mysql",
    aliases: ["mariadb"],
    label: "MySQL / MariaDB",
    dialect: "mysql",
    connection: [
      '  // databaseUrl: Deno.env.get("MYSQL_URL") ?? Deno.env.get("DATABASE_URL"),',
    ],
  },
];

function resolveInitTarget(name: string): InitTarget | undefined {
  const key = name.trim().toLowerCase();
  return INIT_TARGETS.find((target) =>
    target.id === key || target.aliases.includes(key)
  );
}

function initTargetIds(): string {
  return INIT_TARGETS.map((target) => target.id).join(", ");
}

/** Additive DDL generated by a dialect adapter. */
export interface SisalCliGeneratedStatements {
  readonly statements: readonly string[];
  readonly destructive: readonly SchemaChange[];
}

/** Minimal migrator facade used by the CLI. */
export interface SisalCliMigrator {
  migrate(
    options: MigrationRunOptions & {
      readonly migrations: readonly Migration[];
    },
  ): Promise<MigrationResult>;

  plan(options: {
    readonly migrations: readonly Migration[];
  }): Promise<MigrationPlan>;

  applied?(): Promise<unknown>;

  close?(): Promise<void>;
}

/** Dialect adapter hooks used by `sisal` commands. */
export interface SisalCliAdapter {
  generateUpStatements(
    to: SisalSchemaSnapshot,
    from?: SisalSchemaSnapshot,
  ): SisalCliGeneratedStatements;

  createMigrator?(options: {
    readonly config: MigrateConfig;
    readonly dialect: CliDialect;
    readonly logging?: SisalLoggingOptions;
  }): Promise<SisalCliMigrator>;
}

/** Test/runtime injection points for the CLI runner. */
export interface SisalCliOptions {
  readonly config?: MigrateConfig;
  readonly fs?: MigrationFileSystem;
  readonly adapters?: Partial<Record<CliDialect, SisalCliAdapter>>;
  readonly cwd?: string;
  readonly logging?: SisalLogSettings;
  readonly stdout?: CliOutput;
  readonly stderr?: CliOutput;
}

type CliFlagValue = string | boolean | number;

interface ParsedArgs {
  readonly command?: string;
  readonly positionals: readonly string[];
  readonly flags: ReadonlyMap<string, CliFlagValue>;
}

interface CliContext {
  readonly config: MigrateConfig;
  readonly dialect: CliDialect;
  readonly adapter: SisalCliAdapter;
  readonly adapterInjected: boolean;
  readonly fs: MigrationFileSystem;
  readonly logging?: SisalLoggingOptions;
  readonly out: CliOutput;
  readonly err: CliOutput;
}

interface PostgresDdlModule {
  readonly generatePostgresUpStatements:
    SisalCliAdapter["generateUpStatements"];
}

interface PostgresMigrateModule {
  readonly createPgMigrator: (options: {
    readonly url: string;
    readonly historyTable?: string;
    readonly logging?: SisalLoggingOptions;
  }) => Promise<SisalCliMigrator>;
}

interface NeonDdlModule {
  readonly generatePostgresUpStatements:
    SisalCliAdapter["generateUpStatements"];
}

interface NeonMigrateModule {
  readonly createNeonMigrator: (options: {
    readonly url: string;
    readonly historyTable?: string;
    readonly logging?: SisalLoggingOptions;
  }) => Promise<SisalCliMigrator>;
}

interface LibsqlDdlModule {
  readonly generateLibsqlUpStatements: SisalCliAdapter["generateUpStatements"];
}

interface LibsqlMigrateModule {
  readonly createLibsqlMigrator: (options: {
    readonly url: string;
    readonly authToken?: string;
    readonly historyTable?: string;
    readonly logging?: SisalLoggingOptions;
  }) => Promise<SisalCliMigrator>;
}

interface SqliteDdlModule {
  readonly generateSqliteUpStatements: SisalCliAdapter["generateUpStatements"];
}

interface SqliteMigrateModule {
  readonly createSqliteMigrator: (options: {
    readonly path: string;
    readonly historyTable?: string;
    readonly logging?: SisalLoggingOptions;
  }) => Promise<SisalCliMigrator>;
}

interface MysqlDdlModule {
  readonly generateMysqlUpStatements: SisalCliAdapter["generateUpStatements"];
}

interface MysqlMigrateModule {
  readonly createMysqlMigrator: (options: {
    readonly url: string;
    readonly historyTable?: string;
    readonly logging?: SisalLoggingOptions;
  }) => Promise<SisalCliMigrator>;
}

const DEFAULT_CONFIG_FILE = "sisal.migrate.ts";
const DEFAULT_ADAPTER_VERSION = "^0.8.0";
const DEFAULT_MYSQL_ADAPTER_VERSION = "^0.8.0";
const DEFAULT_ADAPTER_IMPORTS = {
  pgDdl: `jsr:@sisal/pg@${DEFAULT_ADAPTER_VERSION}/ddl`,
  pgMigrate: `jsr:@sisal/pg@${DEFAULT_ADAPTER_VERSION}/migrate`,
  neonDdl: `jsr:@sisal/neon@${DEFAULT_ADAPTER_VERSION}/ddl`,
  neonMigrate: `jsr:@sisal/neon@${DEFAULT_ADAPTER_VERSION}/migrate`,
  libsqlDdl: `jsr:@sisal/libsql@${DEFAULT_ADAPTER_VERSION}/ddl`,
  libsqlMigrate: `jsr:@sisal/libsql@${DEFAULT_ADAPTER_VERSION}/migrate`,
  sqliteDdl: `jsr:@sisal/sqlite@${DEFAULT_ADAPTER_VERSION}/ddl`,
  sqliteMigrate: `jsr:@sisal/sqlite@${DEFAULT_ADAPTER_VERSION}/migrate`,
  mysqlDdl: `jsr:@sisal/mysql@${DEFAULT_MYSQL_ADAPTER_VERSION}/ddl`,
  mysqlMigrate: `jsr:@sisal/mysql@${DEFAULT_MYSQL_ADAPTER_VERSION}/migrate`,
} as const;
const VALUE_FLAGS = new Set([
  "config",
  "database-auth-token",
  "database-path",
  "database-url",
  "dialect",
  "dir",
  "history-table",
  "log-level",
  "provider",
  "steps",
  "target",
]);

const HELP = `sisal <command> [options]

Commands:
  init [--target <id>]  Scaffold sisal.migrate.ts for a target database
  generate [name]       Generate an additive SQL migration from config.snapshot
  migrate               Apply pending SQL migrations
  status                Show files, database plan, and drift findings
  drift                 Check whether migrations are clean

Options:
  -c, --config <file>       Config module (default: sisal.migrate.ts)
      --target <id>         init target: ${initTargetIds()}
      --dir <dir>           Override migrations directory
      --dialect <dialect>   postgres, sqlite, or mysql; init also accepts target ids
      --provider <p>        Runtime adapter override (e.g. neon for Neon HTTP)
      --database-url <url>  PostgreSQL URL, libSQL URL, or SQLite path fallback
      --database-auth-token <t>
                            libSQL/Turso auth token
      --database-path <p>   SQLite database path
      --history-table <t>   Migration history table
      --dry-run             Preview migrate without executing
      --steps <n>           Limit migrate to n pending migrations
      --allow-dirty         Run despite checksum mismatches
      --allow-empty         Write an empty generated migration
      --force               Overwrite an existing config on init
      --log-level <level>   silent, error, warn, info, debug, or trace
      --quiet               Suppress non-error command output
  -v, --verbose             Debug logs; repeat or use -vv for trace logs
  -h, --help                Show help`;

/** Runs the `sisal` CLI and returns a process exit code. */
export async function runSisalCli(
  args: readonly string[],
  options: SisalCliOptions = {},
): Promise<number> {
  const out = options.stdout ?? ((line) => console.log(line));
  const err = options.stderr ?? ((line) => console.error(line));

  try {
    const parsed = parseArgs(args);
    validateCliLoggingFlags(parsed);
    const commandOut = cliQuiet(parsed) ? (() => {}) : out;

    if (parsed.flags.get("help") === true || parsed.command === undefined) {
      commandOut(HELP);
      return 0;
    }

    switch (parsed.command) {
      case "init":
        return await commandInit(parsed, {
          ...options,
          stdout: out,
          stderr: err,
        });
      case "generate":
        return await commandGenerate(parsed, {
          ...options,
          stdout: out,
          stderr: err,
        });
      case "migrate":
        return await commandMigrate(parsed, {
          ...options,
          stdout: out,
          stderr: err,
        });
      case "status":
        return await commandStatus(parsed, {
          ...options,
          stdout: out,
          stderr: err,
        });
      case "drift":
        return await commandDrift(parsed, {
          ...options,
          stdout: out,
          stderr: err,
        });
      default:
        err(`Unknown command: ${parsed.command}`);
        err("Run `sisal --help` for usage.");
        return 1;
    }
  } catch (cause) {
    err(cause instanceof Error ? cause.message : String(cause));
    return 1;
  }
}

async function commandInit(
  parsed: ParsedArgs,
  options: SisalCliOptions,
): Promise<number> {
  const rawOut = options.stdout ?? ((line) => console.log(line));
  const out = cliQuiet(parsed) ? (() => {}) : rawOut;
  const err = options.stderr ?? ((line) => console.error(line));
  const fs = options.fs ?? denoMigrationFileSystem();
  const configPath = stringFlag(parsed.flags, "config") ?? DEFAULT_CONFIG_FILE;
  const dir = stringFlag(parsed.flags, "dir") ?? "migrations";
  // `--target` is preferred; `--dialect` is kept as a back-compat alias.
  const targetName = stringFlag(parsed.flags, "target") ??
    stringFlag(parsed.flags, "dialect") ?? "sqlite";
  const target = resolveInitTarget(targetName);

  if (target === undefined) {
    err(
      `Unknown target "${targetName}". Supported targets: ${initTargetIds()}.`,
    );
    return 1;
  }

  if (
    (await fs.readFile(configPath)) !== undefined &&
    parsed.flags.get("force") !== true
  ) {
    err(`${configPath} already exists. Use --force to overwrite.`);
    return 1;
  }

  await fs.writeFile(configPath, renderConfigTemplate(target, dir));
  await fs.mkdir(dir);

  out(`Created ${configPath} (${target.label})`);
  out(`Created ${dir}/`);
  out("Next: define config.snapshot, then run `sisal generate`.");
  return 0;
}

function renderConfigTemplate(target: InitTarget, dir: string): string {
  return `// sisal.migrate.ts — migration config for the \`sisal\` CLI.
//
// SECURITY: this is TRUSTED, executable code. The CLI imports and runs it with
// whatever Deno permissions the command was granted (read/write/env/net/FFI), so
// it can read environment variables, write files, and reach the network. Keep it
// in version control, review changes like any source file, and read secrets from
// the environment (Deno.env.get) rather than hard-coding them.

import { defineConfig } from "@sisal/migrate/workflow";

export default defineConfig({
  dir: ${JSON.stringify(dir)},
  dialect: ${JSON.stringify(target.dialect)},
${
    target.provider === undefined
      ? ""
      : `  provider: ${JSON.stringify(target.provider)},\n`
  }  // snapshot: createSchemaSnapshot({ dialect: ${
    JSON.stringify(target.dialect)
  }, tables: [/* ... */] }),
${target.connection.join("\n")}
});
`;
}

async function commandGenerate(
  parsed: ParsedArgs,
  options: SisalCliOptions,
): Promise<number> {
  const context = await createContext(parsed, options);
  const snapshot = requireSnapshot(context.config, "generate");
  const discovered = await readMigrationsDir(context.fs, context.config.dir);
  const latestSnapshot = latestDiscoveredSnapshot(discovered);
  const { statements, destructive } = context.adapter.generateUpStatements(
    snapshot,
    latestSnapshot,
  );

  if (destructive.length > 0) {
    context.err("Destructive schema changes were detected and withheld:");
    for (const change of destructive) {
      context.err(`  ${formatSchemaChange(change)}`);
    }
    context.err("No migration was written. Handle these changes explicitly.");
    return 1;
  }

  if (statements.length === 0 && parsed.flags.get("allow-empty") !== true) {
    context.out("No schema changes detected. No migration was written.");
    return 0;
  }

  const name = parsed.positionals.join(" ").trim() || "migration";
  const migrationStatements = statements.length === 0
    ? ["select 1"]
    : statements;
  const file = buildMigrationFile({
    sequence: nextMigrationSequence(discovered),
    name,
    statements: migrationStatements,
    snapshot,
  });

  await writeMigrationFile(context.fs, context.config.dir, file);
  context.out(`Created ${joinPath(context.config.dir, file.sqlFileName)}`);
  context.out(`Created ${joinPath(context.config.dir, file.snapshotFileName)}`);

  return 0;
}

async function commandMigrate(
  parsed: ParsedArgs,
  options: SisalCliOptions,
): Promise<number> {
  const context = await createContext(parsed, options);
  const migrator = await createMigrator(context, { requireDatabase: true });
  const discovered = await readMigrationsDir(context.fs, context.config.dir);
  const migrations = discoveredToMigrations(discovered);

  try {
    const result = await migrator.migrate({
      migrations,
      dryRun: parsed.flags.get("dry-run") === true,
      steps: optionalPositiveInteger(parsed.flags.get("steps"), "steps"),
      allowDirty: parsed.flags.get("allow-dirty") === true,
    });

    if (result.dryRun) {
      context.out(
        result.skipped.length === 0
          ? "No pending migrations."
          : `Would apply ${result.skipped.length} migration(s): ${
            result.skipped.join(", ")
          }`,
      );
      return 0;
    }

    context.out(
      result.executed.length === 0
        ? "No pending migrations."
        : `Applied ${result.executed.length} migration(s): ${
          result.executed.map((migration) => migration.id).join(", ")
        }`,
    );

    return 0;
  } finally {
    await migrator.close?.();
  }
}

async function commandStatus(
  parsed: ParsedArgs,
  options: SisalCliOptions,
): Promise<number> {
  const state = await readCliState(parsed, options);

  state.context.out(`${state.discovered.length} migration file(s).`);
  if (state.plan === undefined) {
    state.context.out("Database plan unavailable; no database configured.");
  } else {
    state.context.out(`${state.plan.applied.length} applied migration(s).`);
    state.context.out(`${state.plan.pending.length} pending migration(s).`);
    if (state.plan.hasChecksumMismatches) {
      state.context.out(
        `${state.plan.checksumMismatches.length} checksum mismatch(es).`,
      );
    }
  }

  writeDriftReport(state.context.out, state.report);
  return 0;
}

async function commandDrift(
  parsed: ParsedArgs,
  options: SisalCliOptions,
): Promise<number> {
  const state = await readCliState(parsed, options);
  writeDriftReport(state.context.out, state.report);
  return state.report.clean ? 0 : 1;
}

async function readCliState(
  parsed: ParsedArgs,
  options: SisalCliOptions,
): Promise<{
  readonly context: CliContext;
  readonly discovered: readonly DiscoveredMigration[];
  readonly plan?: MigrationPlan;
  readonly report: DriftReport;
}> {
  const context = await createContext(parsed, options);
  const discovered = await readMigrationsDir(context.fs, context.config.dir);
  const migrations = discoveredToMigrations(discovered);
  const missingSnapshots = discovered
    .filter((migration) => migration.snapshot === undefined)
    .map((migration) => migration.id);
  let plan: MigrationPlan | undefined;
  let migrator: SisalCliMigrator | undefined;

  try {
    if (shouldUseMigrator(context)) {
      migrator = await createMigrator(context, { requireDatabase: false });
      plan = await migrator.plan({ migrations });
    }
  } finally {
    await migrator?.close?.();
  }

  const report = checkDrift({
    currentSnapshot: context.config.snapshot,
    latestSnapshot: discovered.at(-1)?.snapshot,
    pending: plan?.pending.map((item) => item.migration.id),
    migrationsMissingSnapshot: missingSnapshots,
  });

  return {
    context,
    discovered,
    ...(plan === undefined ? {} : { plan }),
    report,
  };
}

async function createContext(
  parsed: ParsedArgs,
  options: SisalCliOptions,
): Promise<CliContext> {
  const rawOut = options.stdout ?? ((line) => console.log(line));
  const out = cliQuiet(parsed) ? (() => {}) : rawOut;
  const err = options.stderr ?? ((line) => console.error(line));
  const config = await loadConfig(parsed, options);
  const dialect = resolveCliDialect(config);
  const injected = options.adapters?.[dialect];
  const adapter = injected ?? await loadDefaultAdapter(dialect, config);
  const logging = createCliLogging(parsed, options, config, rawOut, err);

  return {
    config,
    dialect,
    adapter,
    adapterInjected: injected !== undefined,
    fs: options.fs ?? denoMigrationFileSystem(),
    ...(logging === undefined ? {} : { logging }),
    out,
    err,
  };
}

async function loadConfig(
  parsed: ParsedArgs,
  options: SisalCliOptions,
): Promise<MigrateConfig> {
  const loaded = options.config ?? await importConfig(
    stringFlag(parsed.flags, "config") ?? DEFAULT_CONFIG_FILE,
    options.cwd ?? getCwd(),
  );
  const configuredDialect = stringFlag(parsed.flags, "dialect") ??
    loaded.dialect ?? loaded.snapshot?.dialect;
  const databaseUrl = stringFlag(parsed.flags, "database-url") ??
    loaded.databaseUrl ?? defaultDatabaseUrl(configuredDialect);
  const databaseAuthToken = stringFlag(parsed.flags, "database-auth-token") ??
    loaded.databaseAuthToken ?? getEnv("TURSO_AUTH_TOKEN") ??
    getEnv("LIBSQL_AUTH_TOKEN");
  const databasePath = stringFlag(parsed.flags, "database-path") ??
    loaded.databasePath;

  return defineConfig({
    ...loaded,
    ...(stringFlag(parsed.flags, "dir") === undefined
      ? {}
      : { dir: stringFlag(parsed.flags, "dir")! }),
    ...(stringFlag(parsed.flags, "dialect") === undefined
      ? {}
      : { dialect: stringFlag(parsed.flags, "dialect")! as SisalDialectName }),
    ...(stringFlag(parsed.flags, "provider") === undefined
      ? {}
      : { provider: stringFlag(parsed.flags, "provider")! as MigrateProvider }),
    ...(databaseUrl === undefined ? {} : { databaseUrl }),
    ...(databaseAuthToken === undefined ? {} : { databaseAuthToken }),
    ...(databasePath === undefined ? {} : { databasePath }),
    ...(stringFlag(parsed.flags, "history-table") === undefined
      ? {}
      : { historyTable: stringFlag(parsed.flags, "history-table")! }),
  });
}

function defaultDatabaseUrl(
  dialect: SisalDialectName | string | undefined,
): string | undefined {
  if (dialect === "mysql") {
    return getEnv("MYSQL_URL") ?? getEnv("DATABASE_URL");
  }
  if (dialect === "postgres") {
    return getEnv("DATABASE_URL");
  }
  return getEnv("DATABASE_URL") ?? getEnv("TURSO_DATABASE_URL") ??
    getEnv("LIBSQL_DATABASE_URL");
}

async function importConfig(path: string, cwd: string): Promise<MigrateConfig> {
  const href = toFileUrl(resolvePath(cwd, path)).href;
  const mod = await import(`${href}?v=${Date.now()}`);
  const value = mod.default ?? mod.config;

  if (value === undefined) {
    throw new MigrationError(
      `Migration config ${path} must export default or config`,
      { code: "MIGRATION_INVALID", status: 400 },
    );
  }

  return defineConfig(value as MigrateConfig);
}

async function loadDefaultAdapter(
  dialect: CliDialect,
  config: MigrateConfig,
): Promise<SisalCliAdapter> {
  if (dialect === "postgres" && config.provider === "neon") {
    // Neon keeps PostgreSQL DDL but applies migrations over the serverless/HTTP
    // transport — statement-by-statement (createNeonMigrator's defaults).
    const ddl = await importDefaultAdapterModule<NeonDdlModule>(
      DEFAULT_ADAPTER_IMPORTS.neonDdl,
    );
    const migrate = await importDefaultAdapterModule<NeonMigrateModule>(
      DEFAULT_ADAPTER_IMPORTS.neonMigrate,
    );

    return {
      generateUpStatements: ddl.generatePostgresUpStatements,
      createMigrator(options) {
        if (options.config.databaseUrl === undefined) {
          throw new MigrationError("Neon databaseUrl is required", {
            code: "MIGRATION_DRIVER_MISSING",
            status: 400,
          });
        }

        return migrate.createNeonMigrator({
          url: options.config.databaseUrl,
          historyTable: options.config.historyTable,
          logging: options.logging,
        }) as Promise<SisalCliMigrator>;
      },
    };
  }

  if (dialect === "postgres") {
    const ddl = await importDefaultAdapterModule<PostgresDdlModule>(
      DEFAULT_ADAPTER_IMPORTS.pgDdl,
    );
    const migrate = await importDefaultAdapterModule<PostgresMigrateModule>(
      DEFAULT_ADAPTER_IMPORTS.pgMigrate,
    );

    return {
      generateUpStatements: ddl.generatePostgresUpStatements,
      createMigrator(options) {
        if (options.config.databaseUrl === undefined) {
          throw new MigrationError("PostgreSQL databaseUrl is required", {
            code: "MIGRATION_DRIVER_MISSING",
            status: 400,
          });
        }

        return migrate.createPgMigrator({
          url: options.config.databaseUrl,
          historyTable: options.config.historyTable,
          logging: options.logging,
        }) as Promise<SisalCliMigrator>;
      },
    };
  }

  if (dialect === "mysql") {
    const ddl = await importDefaultAdapterModule<MysqlDdlModule>(
      DEFAULT_ADAPTER_IMPORTS.mysqlDdl,
    );
    const migrate = await importDefaultAdapterModule<MysqlMigrateModule>(
      DEFAULT_ADAPTER_IMPORTS.mysqlMigrate,
    );

    return {
      generateUpStatements: ddl.generateMysqlUpStatements,
      createMigrator(options) {
        if (options.config.databaseUrl === undefined) {
          throw new MigrationError("MySQL databaseUrl is required", {
            code: "MIGRATION_DRIVER_MISSING",
            status: 400,
          });
        }

        return migrate.createMysqlMigrator({
          url: options.config.databaseUrl,
          historyTable: options.config.historyTable,
          logging: options.logging,
        }) as Promise<SisalCliMigrator>;
      },
    };
  }

  if (
    config.databasePath === undefined &&
    isLibsqlDatabaseUrl(config.databaseUrl)
  ) {
    const ddl = await importDefaultAdapterModule<LibsqlDdlModule>(
      DEFAULT_ADAPTER_IMPORTS.libsqlDdl,
    );
    const migrate = await importDefaultAdapterModule<LibsqlMigrateModule>(
      DEFAULT_ADAPTER_IMPORTS.libsqlMigrate,
    );

    return {
      generateUpStatements: ddl.generateLibsqlUpStatements,
      createMigrator(options) {
        if (options.config.databaseUrl === undefined) {
          throw new MigrationError("libSQL databaseUrl is required", {
            code: "MIGRATION_DRIVER_MISSING",
            status: 400,
          });
        }

        return migrate.createLibsqlMigrator({
          url: options.config.databaseUrl,
          authToken: options.config.databaseAuthToken,
          historyTable: options.config.historyTable,
          logging: options.logging,
        }) as Promise<SisalCliMigrator>;
      },
    };
  }

  const ddl = await importDefaultAdapterModule<SqliteDdlModule>(
    DEFAULT_ADAPTER_IMPORTS.sqliteDdl,
  );
  const migrate = await importDefaultAdapterModule<SqliteMigrateModule>(
    DEFAULT_ADAPTER_IMPORTS.sqliteMigrate,
  );

  return {
    generateUpStatements: ddl.generateSqliteUpStatements,
    createMigrator(options) {
      const path = options.config.databasePath ?? options.config.databaseUrl;
      if (path === undefined) {
        throw new MigrationError("SQLite databasePath is required", {
          code: "MIGRATION_DRIVER_MISSING",
          status: 400,
        });
      }

      return migrate.createSqliteMigrator({
        path,
        historyTable: options.config.historyTable,
        logging: options.logging,
      }) as Promise<SisalCliMigrator>;
    },
  };
}

async function importDefaultAdapterModule<TModule>(
  specifier: string,
): Promise<TModule> {
  return await import(specifier) as TModule;
}

async function createMigrator(
  context: CliContext,
  options: { readonly requireDatabase: boolean },
): Promise<SisalCliMigrator> {
  if (context.adapter.createMigrator === undefined) {
    throw new MigrationError(`No migrator adapter for ${context.dialect}`, {
      code: "MIGRATION_DRIVER_MISSING",
      status: 400,
    });
  }

  if (
    options.requireDatabase && !context.adapterInjected &&
    !hasDatabaseConfig(context)
  ) {
    throw new MigrationError(
      `${context.dialect} database configuration is required`,
      { code: "MIGRATION_DRIVER_MISSING", status: 400 },
    );
  }

  return await context.adapter.createMigrator({
    config: context.config,
    dialect: context.dialect,
    logging: context.logging,
  });
}

function shouldUseMigrator(context: CliContext): boolean {
  return context.adapter.createMigrator !== undefined &&
    (context.adapterInjected || hasDatabaseConfig(context));
}

function hasDatabaseConfig(context: CliContext): boolean {
  if (context.dialect === "postgres" || context.dialect === "mysql") {
    return context.config.databaseUrl !== undefined;
  }
  return context.config.databasePath !== undefined ||
    context.config.databaseUrl !== undefined;
}

function isLibsqlDatabaseUrl(value: string | undefined): boolean {
  if (value === undefined) {
    return false;
  }

  return /^(libsql|https?|wss?|file):/i.test(value.trim());
}

function requireSnapshot(
  config: MigrateConfig,
  command: string,
): SisalSchemaSnapshot {
  if (config.snapshot === undefined) {
    throw new MigrationError(`${command} requires config.snapshot`, {
      code: "MIGRATION_INVALID",
      status: 400,
    });
  }

  return config.snapshot;
}

function latestDiscoveredSnapshot(
  discovered: readonly DiscoveredMigration[],
): SisalSchemaSnapshot | undefined {
  const latest = discovered.at(-1);
  if (latest === undefined) {
    return undefined;
  }

  if (latest.snapshot === undefined) {
    throw new MigrationError(
      `Latest migration ${latest.id} has no snapshot file`,
      { code: "MIGRATION_INVALID", status: 400 },
    );
  }

  return latest.snapshot;
}

function discoveredToMigrations(
  discovered: readonly DiscoveredMigration[],
): Migration[] {
  return discovered.map((migration) => {
    const statements = splitSqlStatements(migration.sql);

    if (statements.length > 1) {
      return defineMigration({
        id: migration.id,
        up: statements,
      });
    }

    return defineSqlMigration({
      id: migration.id,
      up: statements[0] ?? migration.sql,
    });
  });
}

function resolveCliDialect(config: MigrateConfig): CliDialect {
  const dialect = config.dialect ?? config.snapshot?.dialect;

  if (dialect === "postgres" || dialect === "sqlite" || dialect === "mysql") {
    return dialect;
  }

  throw new MigrationError(
    "CLI dialect must be postgres, sqlite, or mysql",
    {
      code: "MIGRATION_INVALID",
      status: 400,
      details: { dialect },
    },
  );
}

function writeDriftReport(out: CliOutput, report: DriftReport): void {
  if (report.clean) {
    out("Drift clean.");
    return;
  }

  out("Drift findings:");
  for (const finding of report.findings) {
    out(`  ${finding.kind}: ${finding.message}`);
  }
}

function validateCliLoggingFlags(parsed: ParsedArgs): void {
  resolveCliLogLevelFlag(parsed);
}

function cliQuiet(parsed: ParsedArgs): boolean {
  return parsed.flags.get("quiet") === true;
}

function createCliLogging(
  parsed: ParsedArgs,
  options: SisalCliOptions,
  config: MigrateConfig,
  out: CliOutput,
  err: CliOutput,
): SisalLoggingOptions | undefined {
  const flag = resolveCliLogLevelFlag(parsed);
  const merged = mergeLogSettings(
    config.logging,
    options.logging,
    flag.level === undefined ? undefined : { level: flag.level },
  );

  if (merged === undefined) {
    return undefined;
  }

  return {
    ...merged,
    logger: createCliLogger(out, err),
  };
}

function resolveCliLogLevelFlag(
  parsed: ParsedArgs,
): { readonly level?: SisalLogLevel } {
  const quiet = cliQuiet(parsed);
  const explicitLevel = stringFlag(parsed.flags, "log-level");
  const verbose = verboseFlagCount(parsed.flags);
  const choices = [quiet, explicitLevel !== undefined, verbose > 0]
    .filter(Boolean).length;

  if (choices > 1) {
    throw new MigrationError(
      "Use only one of --quiet, --log-level, or --verbose",
      { code: "MIGRATION_INVALID", status: 400 },
    );
  }

  if (quiet) {
    return { level: "silent" };
  }

  if (explicitLevel !== undefined) {
    if (!isSisalLogLevel(explicitLevel)) {
      throw new MigrationError("Unknown logging level", {
        code: "MIGRATION_INVALID",
        status: 400,
        details: { level: explicitLevel },
      });
    }
    return { level: explicitLevel };
  }

  if (verbose > 0) {
    return { level: verbose > 1 ? "trace" : "debug" };
  }

  return {};
}

function createCliLogger(out: CliOutput, err: CliOutput): Logger {
  return {
    trace: cliLoggerMethod("trace", out),
    debug: cliLoggerMethod("debug", out),
    info: cliLoggerMethod("info", out),
    warn: cliLoggerMethod("warn", err),
    error: cliLoggerMethod("error", err),
  };
}

function cliLoggerMethod(
  methodLevel: Exclude<SisalLogLevel, "silent">,
  sink: CliOutput,
): Logger["debug"] {
  return (
    first: string | Record<string, unknown>,
    second?: string,
  ) => {
    const record = second === undefined || typeof first === "string"
      ? undefined
      : first;
    const message = second ?? String(first);
    const level = logRecordString(record, "level") ?? methodLevel;
    const category = logRecordString(record, "category") ?? "cli";
    const payload = record === undefined ? {} : { ...record };
    delete payload.level;
    delete payload.category;
    const suffix = Object.keys(payload).length === 0
      ? ""
      : ` ${JSON.stringify(payload)}`;

    sink(`[${level}] ${category}: ${message}${suffix}`);
  };
}

function logRecordString(
  record: Record<string, unknown> | undefined,
  key: string,
): string | undefined {
  const value = record?.[key];
  return typeof value === "string" ? value : undefined;
}

function mergeLogSettings(
  ...settingsList: readonly (SisalLogSettings | undefined)[]
): SisalLogSettings | undefined {
  let merged: SisalLogSettings | undefined;

  for (const settings of settingsList) {
    if (settings === undefined) {
      continue;
    }

    merged = {
      ...(merged ?? {}),
      ...(settings.level === undefined ? {} : { level: settings.level }),
      ...(settings.categories === undefined ? {} : {
        categories: { ...(merged?.categories ?? {}), ...settings.categories },
      }),
      ...(settings.sql === undefined
        ? {}
        : { sql: { ...(merged?.sql ?? {}), ...settings.sql } }),
    };
  }

  return merged;
}

function formatSchemaChange(change: SchemaChange): string {
  const table = change.schema === undefined
    ? change.table
    : `${change.schema}.${change.table}`;
  return change.column === undefined
    ? `${change.kind} ${table}`
    : `${change.kind} ${table}.${change.column}`;
}

function parseArgs(args: readonly string[]): ParsedArgs {
  const flags = new Map<string, CliFlagValue>();
  const positionals: string[] = [];

  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];

    if (token === "--") {
      positionals.push(...args.slice(index + 1));
      break;
    }

    if (token === "-h") {
      flags.set("help", true);
      continue;
    }

    if (token === "-c") {
      index += 1;
      flags.set("config", requireFlagValue(args[index], "config"));
      continue;
    }

    if (/^-v+$/.test(token)) {
      incrementVerboseFlag(flags, token.length - 1);
      continue;
    }

    if (token.startsWith("--")) {
      const raw = token.slice(2);
      const equals = raw.indexOf("=");
      const name = equals === -1 ? raw : raw.slice(0, equals);
      const value = equals === -1 ? undefined : raw.slice(equals + 1);

      if (name === "verbose") {
        if (value !== undefined) {
          throw new MigrationError("--verbose does not accept a value", {
            code: "MIGRATION_INVALID",
            status: 400,
          });
        }
        incrementVerboseFlag(flags, 1);
        continue;
      }

      if (VALUE_FLAGS.has(name)) {
        if (value !== undefined) {
          flags.set(name, value);
        } else {
          index += 1;
          flags.set(name, requireFlagValue(args[index], name));
        }
      } else {
        flags.set(name, value ?? true);
      }
      continue;
    }

    positionals.push(token);
  }

  const [command, ...rest] = positionals;
  return { command, positionals: rest, flags };
}

function incrementVerboseFlag(
  flags: Map<string, CliFlagValue>,
  count: number,
): void {
  flags.set("verbose", verboseFlagCount(flags) + count);
}

function requireFlagValue(
  value: string | undefined,
  name: string,
): string {
  if (value === undefined || value.startsWith("-")) {
    throw new MigrationError(`--${name} requires a value`, {
      code: "MIGRATION_INVALID",
      status: 400,
    });
  }

  return value;
}

function stringFlag(
  flags: ReadonlyMap<string, CliFlagValue>,
  name: string,
): string | undefined {
  const value = flags.get(name);
  return typeof value === "string" ? value : undefined;
}

function verboseFlagCount(flags: ReadonlyMap<string, CliFlagValue>): number {
  const value = flags.get("verbose");
  return typeof value === "number" ? value : value === true ? 1 : 0;
}

function optionalPositiveInteger(
  value: CliFlagValue | undefined,
  name: string,
): number | undefined {
  if (value === undefined || value === false) {
    return undefined;
  }

  if (typeof value !== "string") {
    throw new MigrationError(`--${name} requires a number`, {
      code: "MIGRATION_INVALID",
      status: 400,
    });
  }

  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) {
    throw new MigrationError(`--${name} must be a positive integer`, {
      code: "MIGRATION_INVALID",
      status: 400,
    });
  }

  return parsed;
}

function resolvePath(cwd: string, path: string): string {
  if (path.startsWith("/")) {
    return normalizePath(path);
  }

  return normalizePath(`${cwd}/${path}`);
}

function normalizePath(path: string): string {
  const absolute = path.startsWith("/");
  const parts: string[] = [];

  for (const part of path.split("/")) {
    if (part.length === 0 || part === ".") {
      continue;
    }

    if (part === "..") {
      parts.pop();
      continue;
    }

    parts.push(part);
  }

  return `${absolute ? "/" : ""}${parts.join("/")}`;
}

function toFileUrl(path: string): URL {
  const encoded = path.split("/").map(encodeURIComponent).join("/");
  return new URL(`file://${encoded}`);
}

function joinPath(dir: string, name: string): string {
  return dir.endsWith("/") ? `${dir}${name}` : `${dir}/${name}`;
}

function getCwd(): string {
  const deno = (globalThis as { readonly Deno?: { cwd(): string } }).Deno;
  return deno?.cwd() ?? ".";
}

function getEnv(name: string): string | undefined {
  const deno = (globalThis as {
    readonly Deno?: {
      readonly env?: { get(name: string): string | undefined };
    };
  }).Deno;

  try {
    return deno?.env?.get(name);
  } catch {
    return undefined;
  }
}

if (import.meta.main) {
  const deno = (globalThis as {
    readonly Deno?: { readonly args: string[]; exit(code?: number): never };
  }).Deno;
  const code = await runSisalCli(deno?.args ?? []);
  deno?.exit(code);
}
